In [16]:
import torch
import torch.nn as nn
import numpy as np
import cv2
import matplotlib.pyplot as plt


In [14]:
a = torch.rand((3, 8, 40, 40))
torch.prod(torch.tensor(a.shape))
a=a>0.01
# print(a)
torch.sum(a)

tensor(38050)

\ell(x, y) = L = \{l_1,\dots,l_N\}^\top, \quad
        l_n = \left( x_n - y_n \right)^2

In [20]:
im = cv2.imread('E:\\010.tif')
im = cv2.cvtColor(im, cv2.COLOR_BGR2RGB)
# plt.imshow(im)
# plt.show()
a = im[0:50, 0:50]
print(sum(a))

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
